### PR TITLE
Adding PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by dualklip**
If the project is running on PHP 7.4 appears errors related with variables not types
```sh
Type of Vyuldashev\NovaPermission\Role::$title must be string (as in class Laravel\Nova\Resource)
```

This PR fix the issue in PHP 7.4

### CODE REVIEW

**Comment by vyuldashev** [comment]
Released under v3.0.0

**Comment by dualklip** [comment]
Thank you for your approval!

**Comment by argia-andreas** [comment]
@dualklip 
Hi!
Which version of Nova are you running?

We are now getting the opposite problem after this commit :-)
On PHP 7.4 and PHP 8.0
```
Symfony\Component\ErrorHandler\Error\FatalError: Type of Vyuldashev\NovaPermission\Role::$title must not be defined (as in class Laravel\Nova\Resource) in file /vendor/vyuldashev/nova-permission/src/Role.php on line 0
```
For example:
Checking the nova source for Resource.php:
```
    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';
```

and Role.php after this PR:

```
/**     
* The single value that should be used to represent the resource when being displayed.     
*     
* @var string     
*/ 
public static string $title = 'name';
```

Are your version of Nova Resource.php typehinted?
Or am I missing something here?

**Comment by argia-andreas** [comment]
Ok, great! 
Thanks for the quick answer! :-)
I'm not crazy then :-) I was looking through different versions on Nova expecting to find it typehinted in one of them. 
But couldn't find it. Missed the one version where it was typehinted 🙄

Didn't see #160.

Then we'll just wait for a fix to be decided upon.

**Pull request merged**
