### PR TITLE
Ability to publish vendor views

### PR DESCRIPTION
**Pull request by 4unkur**

### CODE REVIEW

**Comment by 4unkur** [comment]
@vyuldashev на packagist оно автоматом зальется?

**Comment by vyuldashev** [comment]
@4unkur Да, v1.9.0

**Comment by rclupes** [comment]
Hi, 
great update!

Could you share the command to publish that views? 
Thank you!

**Comment by 4unkur** [comment]
@rclupes Laravel is smart enough, you can just type:  
```php
php artisan vendor:publish
```
and all the tags will be listed with numbers near them, so you type that number and press enter. That's it )

**Comment by rclupes** [comment]
I knew that command but I thought that work in a different way.
I thought that the tag or the provider was needed.

Thank you! ;)

**Pull request merged**
