### PR TITLE
nova 4 support

### PR DESCRIPTION
**Pull request by sp4r74cus**
Support for Nova 4

Screen Shot 2022-04-07 at 16 50 35
Screen Shot 2022-04-07 at 16 50 50
Screen Shot 2022-04-07 at 16 51 03
Screen Shot 2022-04-07 at 16 51 14
Screen Shot 2022-04-07 at 16 51 22

### CODE REVIEW

**Comment by nasrulhazim** [comment]
can't wait this to be merge!

**Comment by kiritokatklian** [comment]
Hey @sp4r74cus and @nasrulhazim, I'm currently maintaining a fork and merging PRs here [kiritokatklian/nova-permission](https://github.com/kiritokatklian/nova-permission). It just got updated to support Nova 4.

It's a temporary drop in replacement of this package until @vyuldashev has time to update the main repo or decides to drop it altogether, but for now it should do the trick to keep it up to date.

**Comment by sp4r74cus** [comment]
hi @nasrulhazim 
It's possible to use this branch by adding the fork repository to your composer.json (or @kiritokatklian's fork) :
```
   "repositories": [
      {
            "type": "vcs",
            "url": "git@github.com:sp4r74cus/nova-permission.git"
        }
    ]
```

and then run

`composer require vyuldashev/nova-permission:dev-nova-4`

**Comment by sp4r74cus** [comment]
hi @nasrulhazim 
It's possible to use this branch by adding the fork repository to your composer.json (or @kiritokatklian's fork) :
```
   "repositories": [
      {
            "type": "vcs",
            "url": "git@github.com:sp4r74cus/nova-permission.git"
        }
    ]
```

and then run

`composer require vyuldashev/nova-permission:dev-nova-4`

**Comment by kiritokatklian** [comment]
> hi @nasrulhazim It's possible to use this branch by adding the fork repository to your composer.json (or @kiritokatklian's fork) :
> 
> ```
>    "repositories": [
>       {
>             "type": "vcs",
>             "url": "git@github.com:sp4r74cus/nova-permission.git"
>         }
>     ]
> ```
> 
> and then run
> 
> `composer require vyuldashev/nova-permission:dev-nova-4`

My fork is also available on packegist, so you can simply run `composer require kiritokatklian/nova-permission` or replace the one in your composer.json nad run `composer update`

**Comment by lloricode** [comment]
Hi, could you add dev requirement with nova ^4.0?

https://nova.laravel.com/docs/4.0/upgrade.html#updating-composer-dependencies

**Comment by lloricode** [comment]
> Hi, could you add dev requirement with nova ^4.0?
> 
> https://nova.laravel.com/docs/4.0/upgrade.html#updating-composer-dependencies

aw, already been update, nice :+1:

**Comment by amukhin-cyberhull** [comment]
@sp4r74cus maybe that PR also needs to have method input parameters updated in Role.php ?

- fields(**NovaRequest** $request)
- cards(**NovaRequest** $request)
- filters(**NovaRequest** $request)
- lenses(**NovaRequest** $request)
- actions(**NovaRequest** $request)

**Pull request merged**
