### PR TITLE
Fix incompatible types

### LINKED ISSUE #163: Installation issues on v3
Laravel 8.41
Nova 3.25
Spatie 4.01

I have followed installation instructions but I am getting lots of errors, is this package compatible with the latest versions of Nova  and Spatie?

After registering the tool I get the following error, am wondering if I have missed a step!

Type of Vyuldashev\NovaPermission\Role::$title must not be defined (as in class Laravel\Nova\Resource) {"userId":6,"e
xception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Vyuldashev\\NovaPermission\\Role::$title must not be defined
(as in class Laravel\\Nova\\Resource) at /var/www/intranet/vendor/vyuldashev/nova-permission/src/Role.php:0)

Type of Vyuldashev\NovaPermission\Role::$search must not be defined (as in class Laravel\Nova\Resource) {"userId":6,"
exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Vyuldashev\\NovaPermission\\Role::$search must not be define
d (as in class Laravel\\Nova\\Resource) at /var/www/intranet/vendor/vyuldashev/nova-permission/src/Role.php:0)

### PR DESCRIPTION
**Pull request by RVxLab**
Remove type hints for fields as those are not compatible with Laravel\Nova\Resource

Remove type hints for RoleBooleanGroup::fillAttributeFromRequest as this isn't compatible with the base class

Fixes #163

### CODE REVIEW

**Review by jvas28 — COMMENTED** [review]
I think you are missing RoleSelect here :) @RVxLab

**Comment by RVxLab** [comment]
> I think you are missing RoleSelect here :) @RVxLab

Yep, looks like you're correct. I'll fix those when I get home later and go over other files where this may be an issue.

**Comment by RVxLab** [comment]
RoleSelect has also been changed and I double checked everything else. This should be good to go! :)

**Comment by mrbenosborne** [comment]
Can we merge this?

**Comment by RVxLab** [comment]
Pinging @vyuldashev as he probably doesn’t get notified otherwise. 

If you could merge this that’s be grand as this package is actually unusable at this time.

**Pull request merged**
