### PR TITLE
Allow spatie laravel permissions v5.0

### PR DESCRIPTION
**Pull request by SiebeVE**

### CODE REVIEW

**Comment by lloricode** [comment]
1+

**Comment by lloricode** [comment]
before merge this, this needs an update, since spatie permission v5 has team management, and also a BC breaks

**Comment by ralphschindler** [comment]
@vyuldashev looking forward to it working with v5! 👍 😃

**Comment by niekbr** [comment]
Would appreciate a release :)

**Comment by Ahmedd-Ibrahim** [comment]
I made a temporary solution until they look into this,
I forked it and made it in a separate package
https://github.com/Ahmedd-Ibrahim/nova-permission

**Comment by jamespavett** [comment]
> I made a temporary solution until they look into this,
> 
> I forked it and made it in a separate package
> 
> https://github.com/Ahmedd-Ibrahim/nova-permission

Nice but if you look at #174 you will see this was already done by someone else.

**Comment by parallels999** [comment]
Fixed on https://github.com/vyuldashev/nova-permission/commit/891d1c9e305c19f68ff37e278463643dee4070f1

**Pull request closed without merging**
